# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - "functions/**"
      - "deploy-commands-function/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "functions/**"
      - "deploy-commands-function/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build Deploy function
      run: go build -v .
      working-directory: ./deploy-commands-function

    - name: Test Deploy function
      run: go test -v .
      working-directory: ./deploy-commands-function

    - name: Build functions
      run: go build -v .
      working-directory: ./functions

    - name: Test functions
      run: go test -v .
      working-directory: ./functions
