# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - "functions/**"
      - "deploy-commands-function/**"
  pull_request:
    branches: [ "main", "staging" ]
    paths:
      - "functions/**"
      - "deploy-commands-function/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-dir: ["./functions", "./deploy-commands-function"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Build
      run: go build -v
      working-directory: ${{ matrix.go-dir }}
    - name: Test
      run: go test -v
      working-directory: ${{ matrix.go-dir }}
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-dir: ["./functions", "./deploy-commands-function"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.0
        working-directory: ${{ matrix.go-dir }}
